<a href="https://colab.research.google.com/github/mohammedirfan78698/PDS_B15_1997_/blob/main/Lab_2_B15_1997.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

marks = np.array([
    [85, 78, 92],
    [72, 65, 80],
    [90, 88, 95],
    [60, 70, 68],
    [88, 82, 79]
])

print("Student Marks Array:\n", marks)

avg_marks = np.mean(marks)
min_marks = np.min(marks)
max_marks = np.max(marks)

print("\nAverage Marks :", avg_marks)
print("Minimum Marks :", min_marks)
print("Maximum Marks :", max_marks)

print("\nMarks of Student 3:", marks[2])

above_80 = marks > 80
print("\nBoolean Array (True if mark > 80):\n", above_80)

subject_wise = marks.T
print("\nSubject-wise Performance (rows = subjects):\n", subject_wise)

for i, subject in enumerate(subject_wise, start=1):
    print(f"\nSubject {i} -> Avg: {np.mean(subject)}, Min: {np.min(subject)}, Max: {np.max(subject)}")


Student Marks Array:
 [[85 78 92]
 [72 65 80]
 [90 88 95]
 [60 70 68]
 [88 82 79]]

Average Marks : 79.46666666666667
Minimum Marks : 60
Maximum Marks : 95

Marks of Student 3: [90 88 95]

Boolean Array (True if mark > 80):
 [[ True False  True]
 [False False False]
 [ True  True  True]
 [False False False]
 [ True  True False]]

Subject-wise Performance (rows = subjects):
 [[85 72 90 60 88]
 [78 65 88 70 82]
 [92 80 95 68 79]]

Subject 1 -> Avg: 79.0, Min: 60, Max: 90

Subject 2 -> Avg: 76.6, Min: 65, Max: 88

Subject 3 -> Avg: 82.8, Min: 68, Max: 95
