<a href="https://colab.research.google.com/github/mohammedirfan78698/PDS_B15_1997_/blob/main/Lab_3_B15_1997.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

add_result = np.add(A, B)
sub_result = np.subtract(A, B)

print("\nMatrix Addition:\n", add_result)
print("\nMatrix Subtraction:\n", sub_result)

print("\nManual Check (A[0,0] + B[0,0]):", A[0,0] + B[0,0])
print("Manual Check (A[0,0] - B[0,0]):", A[0,0] - B[0,0])


Matrix A:
 [[9 5 1]
 [2 2 3]
 [5 8 8]]
Matrix B:
 [[6 8 2]
 [1 5 5]
 [8 8 2]]

Matrix Addition:
 [[15 13  3]
 [ 3  7  8]
 [13 16 10]]

Matrix Subtraction:
 [[ 3 -3 -1]
 [ 1 -3 -2]
 [-3  0  6]]

Manual Check (A[0,0] + B[0,0]): 15
Manual Check (A[0,0] - B[0,0]): 3


In [2]:
import numpy as np

X = np.random.randint(1, 10, (3, 2))
Y = np.random.randint(1, 10, (2, 3))

print("Matrix X (3x2):\n", X)
print("Matrix Y (2x3):\n", Y)

dot_result = np.dot(X, Y)

print("\nDot Product Result (3x3):\n", dot_result)

print("\nManual Check (X[0] dot Y[:,0]):", np.dot(X[0], Y[:,0]))


Matrix X (3x2):
 [[5 6]
 [9 2]
 [3 3]]
Matrix Y (2x3):
 [[8 1 3]
 [3 7 2]]

Dot Product Result (3x3):
 [[58 47 27]
 [78 23 31]
 [33 24 15]]

Manual Check (X[0] dot Y[:,0]): 58
